name: daily-cron
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    # push:
    #   branches:
    #     - mainjobs:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://recharts-next-material-mongo.vercel.app/api/stats' \
          --header 'Authorization: Bearer ${{ secrets.APP_API_KEY }}'
